version: 2
defaults: &defaults
  docker:
    - image: circleci/openjdk:8-jdk

install_awscli: &install_awscli
  name: "Install awscli"
  command: |
    sudo apt-get update
    sudo apt-get install python-pip
    sudo pip install awscli awsebcli
    aws --version
    eb --version
  
deploy_steps: &deploy_steps
  - checkout
  - attach_workspace:
      at: .
  - run: *install_awscli
  - setup_remote_docker
  - run: ls
  - run: find ./service/target
  - run: .deploy/ebs_deploy.sh tc-billing-account-service $DEPLOY_ENV $CIRCLE_BUILD_NUM

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: cd service && mvn clean package integration-test
      - persist_to_workspace:
          root: .
          paths:
            - ./service/target

  deploy_prod:
    <<: *defaults
    environment:
      DEPLOY_ENV: "PROD"
    steps: *deploy_steps

  deploy_dev:
    <<: *defaults
    environment:
      DEPLOY_ENV: "DEV"
    steps: *deploy_steps
      

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy_dev:
          filters:
            branches:
              only: dev
          requires:
            - build
      - deploy_prod:
          filters:
            branches:
              only: master
          requires:
            - build